name: Continuos Integration
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0
      
      - name: Start mail mock server
        run: npm run start:mock

      - name: npm-ci
        run: npm ci

      - name: unit
        run: npm run test:unit

      - name: build
        run: npm run build

      - name: test-api
        run: |
          npm start &
          npm run test:api
