name: Continuos Integration
on:
  push:
  workflow_dispatch:

env:
  TODOLIST_BACKEND_URL: http://localhost:8080
  WEBSITE_URL: http://localhost:3000
  SERVER_URL: http://localhost:4000
  PORT: 4000
  SEND_VERIFICATION_EMAIL_URL: DESKTOP-MRA7G1L
  SMTP_PORT: 3005
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_MAIL: ${{ secrets.SMTP_MAIL }}

jobs:
  build:
    name: Build
    environment: ENV_FILE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: npm-ci
        run: npm ci

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0
      
      - name: Start mail mock server
        run: npm run start:mock &

      - name: unit
        run: npm run test:unit

      - name: build
        run: npm run build

      - name: server start
        run: |
          npm start &
          npm run test:api
          
